<?php
/**
 * System generated by SysGen (System Generator with Formdin Framework) 
 * Download SysGen: https://github.com/bjverde/sysgen
 * SysGen  Version: 0.6.1-alpha
 * FormDin Version: 4.2.3-alpha
 * 
 * System requisicaovm created in: 2018-05-09 19:48:41
 */

$perfilBancoAdm  = ServidorConfig::getInstancia()->getPerfilAdm();

define('BANCO'   , $perfilBancoAdm['DBMS']);
define('PORT'    , $perfilBancoAdm['PORT']);
define('HOST'    , $perfilBancoAdm['HOST']);
define('DATABASE', $perfilBancoAdm['DATABASE']);
define('SCHEMA'  , '');
define('USUARIO' , $perfilBancoAdm['USERNAME']);
define('SENHA'   , $perfilBancoAdm['PASSWORD']);
define('UTF8_DECODE'   , 0);

?>