<?php
/**
 * System generated by SysGen (System Generator with Formdin Framework) 
 * Download SysGen: https://github.com/bjverde/sysgen
 * SysGen  Version: 0.6.1-alpha
 * FormDin Version: 4.2.3-alpha
 * 
 * System requisicaovm created in: 2018-05-09 19:48:41
 */

$ambiente  = ServidorConfig::getInstancia()->getConfigParam('ambiente');
if( $ambiente == 'produção' || $ambiente == 'producao' ) {
    $ambiente = null;
}

define('SYSTEM_NAME'    , 'Carga PDF Seu Mestre');
define('SYSTEM_NAME_SUB', $ambiente);
define('SYSTEM_ACRONYM' , 'sm');
define('SYSTEM_VERSION' , '0.0.0');
define('APLICATIVO'     , SYSTEM_ACRONYM);
if ( !defined('DS') ){ define('DS'   , DIRECTORY_SEPARATOR); }

define('DIR_ARQ_DIARIO', ServidorConfig::getInstancia()->getConfigParam('pasta_dados'));
define('URL_DADOS'     , ServidorConfig::getInstancia()->getConfigParam('url_dados'));
?>