<?php
/**
 * System generated by SysGen (System Generator with Formdin Framework) 
 * Download SysGen: https://github.com/bjverde/sysgen
 * SysGen  Version: 0.6.1-alpha
 * FormDin Version: 4.2.3-alpha
 * 
 * System requisicaovm created in: 2018-05-09 19:48:51
 */

$menu = new TMenuDhtmlx();
$menu->add('1', null, 'Menu', null, null, 'menu-alt-512.png');
$menu->add('1.2',1,'Carga','modulos/carga.php');

$menu->add('9', null, 'Sobre', 'modulos/sys_about.php', null, 'information-circle.jpg');


$menu->getXml();
?>