<?php
/**
 * System generated by SysGen (System Generator with Formdin Framework) 
 * Download SysGen: https://github.com/bjverde/sysgen
 * SysGen  Version: 0.6.1-alpha
 * FormDin Version: 4.2.3-alpha
 * 
 * System requisicaovm created in: 2018-05-09 19:48:41
 */

//Constantes e configurações
require_once('classes/ServidorConfig.class.php');

require_once('includes/constantes.php');
require_once('includes/config_conexao.php');

//FormDin version: 4.2.3-alpha
require_once('../base/classes/webform/TApplication.class.php');
require_once('classes/autoload_testmongo.php');

//Composer
require_once __DIR__ . "/vendor/autoload.php";

define('RAIZ_APP',__DIR__);

$app = new TApplication(); // criar uma instancia do objeto aplicacao
$app->setTitle(SYSTEM_NAME);
$app->setSubtitle(SYSTEM_NAME_SUB);
$app->setSigla(SYSTEM_ACRONYM);
$app->setVersionSystem(SYSTEM_VERSION);

//Para testar com outro login basta informar o login desejado
//define('SYSTEM_USER' , 'pedro.correa');
/*
define('SYSTEM_USER' , ServerHelper::get('PHP_AUTH_USER'));
$app->setLoginInfo(SYSTEM_USER);
if ( Acesso::usuarioAutorizado(SYSTEM_USER) ) {
    $app->setMainMenuFile('includes/menu.php');
}
$app->setHeaderContent('index_header.php');
$app->setWaterMark('images/bg_transparencia.jpg');
*/
$app->setMainMenuFile('includes/menu.php');
$app->run();
?>