<?php
/**
 * System generated by SysGen (System Generator with Formdin Framework) 
 * Download SysGen: https://github.com/bjverde/sysgen
 * SysGen  Version: 0.6.1-alpha
 * FormDin Version: 4.2.3-alpha
 * 
 * System requisicaovm created in: 2018-05-09 19:48:41
 */

if ( !function_exists( 'requisicaovm_autoload') ) {
	function requisicaovm_autoload( $class_name )	{
		require_once $class_name . '.class.php';
	}
spl_autoload_register('requisicaovm_autoload');
}